name: Publish

on:
    push:
        paths:
            - "package.json"
        branches:
            - main

jobs:
    publish:
        permissions:
            contents: write
        name: Publish to NPM
        runs-on: ubuntu-latest
        outputs:
            release_id: ${{ steps.release.outputs.releaseID }}
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
              with:
                fetch-depth: 0
            - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
              with:
                registry-url: 'https://registry.npmjs.org'
            - name: Build package
              run: |
                yarn
                yarn build
            - name: Zip Dist
              run: |
                cd dist
                zip -r ../dist.zip .
                cd ..
            - name: Get package version
              id: get_version
              run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
            - name: Make release
              id: release
              uses: Kas-tle/base-release-action@95bf169cd0975b3fba91535309d416801aa97a38
              with:
                files: |
                  dist/dist.zip
                releaseName: ${{ steps.get_version.outputs.version }}
                appID: ${{ secrets.RELEASE_APP_ID }}
                appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
            - run: yarn publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    upload-logs:
        permissions:
            contents: write
        name: Upload Logs
        runs-on: ubuntu-latest
        needs: publish
        steps:
            - uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                releaseID: ${{ needs.publish.outputs.release_id }}